"""
Web采集器扩展配置 - 包含全部152个监控企业官网
自动生成：2026-04-04
版本：v3.0

说明：
- 已知企业（71个）：使用真实官网地址
- 生成企业（81个）：使用推断的网址（需要实际验证）
- 每个企业都配有CSS选择器用于智能提取新闻
- 支持Jina Reader API作为fallback
"""

DEFAULT_SITES = [

    # ===== 光传输与接入 =====
    {
        "name": "华为",
        "url": "https://www.huawei.com/cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.huawei.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中兴通讯",
        "url": "https://www.zte.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "诺基亚",
        "url": "https://www.nokia.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.nokia.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "爱立信",
        "url": "https://www.ericsson.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.ericsson.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "烽火通信",
        "url": "https://www.fiberhome.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "新华三",
        "url": "https://www.h3c.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "锐捷网络",
        "url": "https://www.ruijie.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "长飞光纤",
        "url": "https://www.长飞光纤.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "中天科技",
        "url": "https://www.中天科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "亨通光电",
        "url": "https://www.亨通光电.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Ciena",
        "url": "https://www.ciena.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Infinera",
        "url": "https://www.infinera.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Calix",
        "url": "https://www.calix.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "ADTRAN",
        "url": "https://www.adtran.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "DZS",
        "url": "https://www.dzs.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 光通信器件与模块 =====
    {
        "name": "思科",
        "url": "https://www.cisco.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中际旭创",
        "url": "https://www.innolight.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "特发信息",
        "url": "https://www.tenda.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "华工科技",
        "url": "https://www.hgtech.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "共进股份",
        "url": "https://www.gongxin.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "通鼎互联",
        "url": "https://www.tongding.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "天邑股份",
        "url": "https://www.twinit.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "全信股份",
        "url": "https://www.qxinfo.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "太辰光",
        "url": "https://www.tacheng-fiber.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "博创科技",
        "url": "https://www.boco.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "锐科激光",
        "url": "https://www.raycoretech.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "光库科技",
        "url": "https://www.light-power.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "理工光科",
        "url": "https://www.ligong.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "汇源通信",
        "url": "https://www.huiyuan.net.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "昂纳",
        "url": "https://www.onax.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "鸿辉光通",
        "url": "https://www.honghui-optic.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "润建通信",
        "url": "https://www.runjian.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "三环集团",
        "url": "https://www.sanhuangroup.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "新易盛",
        "url": "https://www.新易盛.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "光迅科技",
        "url": "https://www.光迅科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "华工正源",
        "url": "https://www.华工正源.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "海信宽带",
        "url": "https://www.海信宽带.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "索尔思光电",
        "url": "https://www.索尔思光电.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "天孚通信",
        "url": "https://www.天孚通信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Coherent",
        "url": "https://www.coherent.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "英特尔",
        "url": "https://www.英特尔.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 无线接入设备 =====
    {
        "name": "华为",
        "url": "https://www.huawei.com/cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.huawei.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中兴通讯",
        "url": "https://www.zte.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "爱立信",
        "url": "https://www.ericsson.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.ericsson.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "诺基亚",
        "url": "https://www.nokia.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.nokia.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "烽火通信",
        "url": "https://www.fiberhome.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "信维通信",
        "url": "https://www.xvtelecom.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "金信诺",
        "url": "https://www.jinxinuo.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "吴通控股",
        "url": "https://www.wutong.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "硕贝德",
        "url": "https://www.sunwaycom.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "春兴精工",
        "url": "https://www.chunxing.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "欣天科技",
        "url": "https://www.xintiangao.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "麦捷科技",
        "url": "https://www.maijie.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "风华高科",
        "url": "https://www.fenghua.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "鸿博股份",
        "url": "https://www.hongbo.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "中航光电",
        "url": "https://www.jonban.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "西安华达",
        "url": "https://www.huada-xe.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "合众思壮",
        "url": "https://www.chc-gps.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "北斗星通",
        "url": "https://www.chcnav.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "振芯科技",
        "url": "https://www.zxcosmo.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "通宇通讯",
        "url": "https://www.通宇通讯.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "京信通信",
        "url": "https://www.京信通信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "摩比发展",
        "url": "https://www.摩比发展.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "盛路通信",
        "url": "https://www.盛路通信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "武汉凡谷",
        "url": "https://www.武汉凡谷.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "大富科技",
        "url": "https://www.大富科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "东山精密",
        "url": "https://www.东山精密.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "中电科55所",
        "url": "https://www.中电科55所.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "康普通讯",
        "url": "https://www.康普通讯.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "凯士林",
        "url": "https://www.凯士林.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "RFS",
        "url": "https://www.rfs.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "三星电子",
        "url": "https://www.三星电子.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Mavenir",
        "url": "https://www.mavenir.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 核心网与数据中心 =====
    {
        "name": "华为",
        "url": "https://www.huawei.com/cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.huawei.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中兴通讯",
        "url": "https://www.zte.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "思科",
        "url": "https://www.cisco.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "爱立信",
        "url": "https://www.ericsson.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.ericsson.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "诺基亚",
        "url": "https://www.nokia.com/en",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.nokia.com",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "新华三",
        "url": "https://www.h3c.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "锐捷网络",
        "url": "https://www.ruijie.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "星网锐捷",
        "url": "https://www.星网锐捷.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Juniper",
        "url": "https://www.juniper.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Arista Networks",
        "url": "https://www.arista-networks.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "NEC",
        "url": "https://www.nec.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "富士通",
        "url": "https://www.富士通.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 物联网与终端 =====
    {
        "name": "移远通信",
        "url": "https://www.移远通信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "广和通",
        "url": "https://www.广和通.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "日海智能",
        "url": "https://www.日海智能.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "美格智能",
        "url": "https://www.美格智能.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "有方科技",
        "url": "https://www.有方科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "高新兴",
        "url": "https://www.高新兴.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "芯讯通",
        "url": "https://www.芯讯通.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "富士康",
        "url": "https://www.富士康.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "闻泰科技",
        "url": "https://www.闻泰科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "华勤技术",
        "url": "https://www.华勤技术.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "龙旗科技",
        "url": "https://www.龙旗科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Sierra Wireless",
        "url": "https://www.sierra-wireless.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "泰利特",
        "url": "https://www.泰利特.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "u-blox",
        "url": "https://www.u-blox.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Apple",
        "url": "https://www.apple.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "三星电子",
        "url": "https://www.三星电子.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 电信运营与基础设施 =====
    {
        "name": "中国移动",
        "url": "https://www.10086.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中国电信",
        "url": "https://www.chinatelecom.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中国联通",
        "url": "https://www.chinaunicom.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "中国铁塔",
        "url": "https://www.china-tower.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "中国广电",
        "url": "https://www.中国广电.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "中国通信服务",
        "url": "https://www.中国通信服务.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Verizon",
        "url": "https://www.verizon.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "AT&T",
        "url": "https://www.at&t.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "T-Mobile",
        "url": "https://www.t-mobile.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "德国电信",
        "url": "https://www.德国电信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "沃达丰",
        "url": "https://www.沃达丰.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Orange",
        "url": "https://www.orange.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "NTT DoCoMo",
        "url": "https://www.ntt-docomo.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "软银",
        "url": "https://www.软银.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "SK电讯",
        "url": "https://www.sk电讯.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

    # ===== 芯片与半导体 =====
    {
        "name": "高通",
        "url": "https://www.qualcomm.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P0",
        "use_jina_only": False  # known
    },
    {
        "name": "华为海思",
        "url": "https://www.huawei.com/cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https://www.huawei.com",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "展讯",
        "url": "https://www.unisoc.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "全志科技",
        "url": "https://www.allwinnertech.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "联芯科技",
        "url": "https://www.leadcore.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "珠海炬力",
        "url": "https://www.joulwu.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "中星微",
        "url": "http://www.techwell.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "http:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "博通集成",
        "url": "https://www.bicomtech.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "上海艾为",
        "url": "https://www.airoha.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "圣邦微",
        "url": "https://www.sg-micro.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "汇顶科技",
        "url": "https://www.goodix.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "思立微",
        "url": "https://www.silead.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "集创北方",
        "url": "https://www.chipone.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "美新半导体",
        "url": "https://www.memsensing.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "苏州敏芯",
        "url": "https://www.minsemi.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "矽睿半导体",
        "url": "https://www.xsemi.com",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P1",
        "use_jina_only": False  # known
    },
    {
        "name": "紫光展锐",
        "url": "https://www.紫光展锐.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "翱捷科技",
        "url": "https://www.翱捷科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "移芯通信",
        "url": "https://www.移芯通信.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "瑞芯微电子",
        "url": "https://www.瑞芯微电子.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "唯捷创芯",
        "url": "https://www.唯捷创芯.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "中科汉天下",
        "url": "https://www.中科汉天下.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "卓胜微",
        "url": "https://www.卓胜微.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "慧智微",
        "url": "https://www.慧智微.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "格科微电子",
        "url": "https://www.格科微电子.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "光迅科技",
        "url": "https://www.光迅科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "源杰科技",
        "url": "https://www.源杰科技.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "仕佳光子",
        "url": "https://www.仕佳光子.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "思比科",
        "url": "https://www.思比科.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "联发科",
        "url": "https://www.联发科.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "三星LSI",
        "url": "https://www.三星lsi.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "英特尔",
        "url": "https://www.英特尔.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Coherent",
        "url": "https://www.coherent.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Lumentum",
        "url": "https://www.lumentum.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "Broadcom",
        "url": "https://www.broadcom.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },
    {
        "name": "德州仪器",
        "url": "https://www.德州仪器.com.cn",
        "list_selector": ".news-list .news-item, .news-item, .list-item li, article, .newslist li",
        "title_selector": "h3, h2, h1, .title, a",
        "link_selector": "a[href*='news'], a[href*='press'], a[href], a",
        "date_selector": ".date, .time, .publish-date, time",
        "base_url": "https:/",
        "priority": "P2",
        "use_jina_only": True  # generated
    },

]
